---
- name: Install Nginx
  apt: name=nginx state=latest

- name: Copy nginx configuration
  template: src={{ rails_env }}.conf  dest=/etc/nginx/sites-enabled/{{ deploy_app_name }}.conf owner=root group=root
  notify: restart nginx

- name: Disable default config
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx


