- name: set hostname
  hostname: name="{{ deploy_app_name }}-{{ hostname_suffix|quote }}"

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ deploy_app_name }}-{{ hostname_suffix|quote }}"
    state: present
