- name: set locale to {{locale}}
  command: /usr/sbin/update-locale LANG={{locale}} LC_ALL={{locale}}

- name: set timedatectl to {{ timezone }}
  command: timedatectl set-timezone {{ timezone }}

- name: set /etc/localtime to {{ timezone  }}
  copy:
    src: /usr/share/zoneinfo/{{ timezone }}
    dest: /etc/localtime

- name: set /etc/timezone to {{ timezone  }}
  template: src=etc/timezone dest=/etc/timezone
  notify: update tzdata
